Add homework lesson-08
Web-Laboratory-Ordynski/cobra-02 pull request #16
Opened 2020-07-03 08:45 UTC by yyavorskaia

2020-07-03 13:42 UTC, AlexOrd requested changes

2020-07-03 13:42 UTC, AlexOrd commented on homework/yuliya-yavorskaia/lesson-08/01/css/style.css
> +  font-display: swap;
Cool )

2020-07-03 13:42 UTC, AlexOrd commented on homework/yuliya-yavorskaia/lesson-08/01/css/style.css
> +/*.blog__item::after {
Comments.

2020-07-03 13:42 UTC, AlexOrd commented on homework/yuliya-yavorskaia/lesson-08/01/less/style.less
> +/*.blog__item::after {
comments

2020-07-08 17:18 UTC, Towko approved these changes

2020-07-08 17:18 UTC, Towko commented on homework/yuliya-yavorskaia/lesson-08/01/img/day.svg
> +
too much spaces

2020-07-08 17:18 UTC, Towko commented on homework/yuliya-yavorskaia/lesson-08/01/index.html
> +    integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
???

2020-07-08 18:22 UTC, yyavorskaia commented on homework/yuliya-yavorskaia/lesson-08/01/index.html
> +    integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
Подключила Bootstrap по ссылкам CDN.

2020-07-08 18:23 UTC, yyavorskaia commented on homework/yuliya-yavorskaia/lesson-08/01/index.html
> +    integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
Они предлагают такой подход как вариант,

2020-07-20 16:43 UTC, merged