added homework and changed index.html
Web-Laboratory-Ordynski/cobra-02 pull request #19
Opened 2020-07-06 13:54 UTC by tania833

2020-07-08 17:27 UTC, Towko requested changes

2020-07-08 17:27 UTC, Towko commented on homework/tetiana-polishchuk/lesson-09/Task-1/style.css
> +    max-width: 1163px;
strange width

2020-07-08 17:27 UTC, Towko commented on homework/tetiana-polishchuk/lesson-09/Task-2/style.css
> +
Лучше ширину задавать не body а контейнеру внутри. Не знаю насколько это правильно или нет, но такой интерпретации не видел никогда: padding - возможно, margin для body? сомнительное применение, max-width - аналогично
body --> header -->  div.container {max-width: 1116px; margin: 150px auto;}

2020-07-08 17:27 UTC, Towko commented on homework/tetiana-polishchuk/lesson-09/Task-2/style.css
> +    src: url('./fonts/Proxima\ Nova\ Regular.otf') format('opentype');
работает?

2020-07-09 16:56 UTC, tania833 commented on homework/tetiana-polishchuk/lesson-09/Task-1/style.css
> +    max-width: 1163px;
Така була зазначена в макеті, чи не потрібно прямо як там зазначати?

2020-07-09 16:58 UTC, tania833 commented on homework/tetiana-polishchuk/lesson-09/Task-2/style.css
> +    src: url('./fonts/Proxima\ Nova\ Regular.otf') format('opentype');
Так!!! :)

2020-07-20 16:48 UTC, merged